name: Detekt

on:
  push:
    branches: [ "main" ]
jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: Run a one-line script
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle
      - name: +x for gradle
        run: chmod +x ./gradlew
      - name: checking with detekt
        run: ./gradlew :app:detekt
